### ISSUE TITLE
Tiempo de pausa

### ISSUE THREAD

**Issue by Ajicancha** [doriamflores/triviamedicina#2]
Creo que sería buena opción reducir el tiempo de pausa entre cada pregunta porque demora demasiado. Quizá 1 segundo o 2 máximo. Actualmente, parecen 3 o 4 segundos

**Comment by doriamflores** [comment]
acabo de corregir el issue para que la espera entre cada pregunta no sea tan aburrida, pero no se olviden leer la info que se muestra después de responder cada pregunta
